# Generated by Django 3.2.3 on 2021-06-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LInfo',
            fields=[
                ('loc_hosCode', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_hosName', models.CharField(max_length=50)),
                ('loc_hosClassName', models.CharField(max_length=50)),
                ('loc_hosCityName', models.CharField(max_length=50)),
                ('loc_hosCountyName', models.CharField(max_length=50)),
                ('loc_zipCode', models.CharField(max_length=50)),
                ('loc_hosAddress', models.CharField(max_length=50)),
                ('loc_hosPhoneNumber', models.CharField(max_length=50)),
                ('loc_hosUrl', models.CharField(max_length=50)),
                ('loc_hosEstablishment', models.CharField(max_length=50)),
                ('loc_Latitude', models.FloatField()),
                ('loc_longitude', models.FloatField()),
            ],
        ),
    ]
