# Generated by Django 3.2.3 on 2021-06-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linfo',
            name='loc_hosAddress',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='linfo',
            name='loc_hosUrl',
            field=models.CharField(max_length=100),
        ),
    ]
