# Generated by Django 3.2.3 on 2021-06-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationInfo', '0002_auto_20210601_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linfo',
            name='loc_Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='linfo',
            name='loc_longitude',
            field=models.FloatField(null=True),
        ),
    ]
