# Generated by Django 3.2.3 on 2021-06-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationInfo', '0003_auto_20210601_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linfo',
            name='loc_hosUrl',
            field=models.CharField(max_length=200),
        ),
    ]
