# Generated by Django 3.2.3 on 2021-06-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationInfo', '0004_alter_linfo_loc_hosurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linfo',
            options={'verbose_name': 'locInfo', 'verbose_name_plural': 'locInfo'},
        ),
    ]
